name:                ProofsAsPrograms
version:             0.1.0.0
github:              "githubuser/ProofsAsPrograms"
license:             BSD3
author:              "Joachim Tilsted Kristensen"
maintainer:          "joachkr@ifi.uio.no"
copyright:           "2022 Joachim Tilsted Kristensen"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
